// src/components/game/Game.svelte
<div id="game">
  <!-- <RegistrationForm v-if="step == 1" @submitData="changeStep(2)" ref="registrationForm"/> -->
  {#if step == 2}
    <SetPassword v-if="step == 2" on:pay={() => changeStep(3)}/>
  {/if}
  {#if step == 3}
    <Pay on:pay={() => finish}/>
  {/if}

</div>

<script>
  import SetPassword from './SetPassword.svelte'
  import Pay from './Pay.svelte'
  import { createEventDispatcher } from "svelte"
  const dispatch = createEventDispatcher()

  /* data */
  let step = 3

  /* methods */
  function changeStep(step) {
    step = step
  }
  function finish() {
    dispatch('finish')
  } 
</script>

// src/components/Game/Game.vue
<template>
  <div id="game">
    <RegistrationForm v-if="step == 1" @submitData="changeStep(2)" ref="registrationForm"/>
    <SetPassword v-if="step == 2" @pay="changeStep(3)"/>
    <Pay v-if="step == 3" @pay="finish()"/>
  </div>
</template>

<script>
import RegistrationForm from './RegistrationForm.vue'
import SetPassword from './SetPassword.vue'
import Pay from './Pay.vue'

export default {
  components: {
    RegistrationForm,
    SetPassword,
    Pay
  },
  data: () => ({
    step: 1
  }),
  methods: {
    changeStep (step) {
      this.step = step
    },
    finish () {
      this.$emit('finish')
    }
  }
}
</script>
