// src/components/Game/IdleCheck.vue
<template>
  <div class="modal bg-teal-600 z-50 shadow-2xl">
    <p class="text-4xl text-right mb-5">Are you still there?</p>
    <label>Type "Yes" (exactly) if you are still there</label>
    <input type="text" placeholder='Type "Yes" if you are still there' class="w-full py-2 px-4 text-black" v-model="answer" ref="textbox">
    <div class="block" v-if="answer == 'Yes'">
      <button class="btn primary" @click="answer = 'No, I am not NOT OUT here. Sorry!!!!!!!!!!!!'">Accept reset</button>
      <button class="btn danger" @click="closeMe()">Reject insubmission</button>
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    answer: 'No, I am not NOT OUT here. Sorry!!!!!!!!!!!!'
  }),
  inject: ['toggleIdleCheck'],
  methods: {
    closeMe () {
      this.toggleIdleCheck(false)
    }
  },
  mounted () {
    this.$refs.textbox.focus()
  }
}
</script>

// src/components/game/IdleCheck.svelte
<div class="modal bg-teal-600 z-50 shadow-2xl">
  <p class="text-4xl text-right mb-5">Are you still there?</p>
  <!-- svelte-ignore a11y-label-has-associated-control -->
  <label>Type "Yes" (exactly, including the case) if you are still there</label>
  <input type="text" placeholder='Type "Yes" if you are still there' class="w-full py-2 px-4 text-black" bind:value={answer} id="idleTextbox">
  {#if answer == 'Yes'}
    <div class="block">
      <button class="btn primary" on:click={() => answer = 'No, I am not NOT OUT here. Sorry!!!!!!!!!!!!'}>Accept reset</button>
      <button class="btn danger" on:click={() => toggleIdleCheck(false)}>Reject insubmission</button>
    </div>
  {/if}
</div>

<script>
import { onMount } from "svelte";


  /* props */
  export let toggleIdleCheck

  /* data */
  let answer = 'No, I am not NOT OUT here. Sorry!!!!!!!!!!!!'

  /* lifecycle */
  onMount(() => {
    let textbox = document.querySelector('#idleTextbox')
    textbox.focus()
  })
</script>
